<a href="https://colab.research.google.com/github/deepsharma26/SIRT1/blob/Descriptor_gen/SubstructureCount_mol_fp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip -o fingerprints_xml.zip

--2025-02-05 16:23:44--  https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip [following]
--2025-02-05 16:23:44--  https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘fingerprints_xml.zip.1’

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0s

2025-02-05 16:23:44 (84.8 MB/s) - ‘fingerprints_xml.zip.1’ saved [10871/10871]

Archive:  fingerprints_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [15]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

['AtomPairs2DFingerprintCount.xml',
 'AtomPairs2DFingerprinter.xml',
 'EStateFingerprinter.xml',
 'ExtendedFingerprinter.xml',
 'Fingerprinter.xml',
 'GraphOnlyFingerprinter.xml',
 'KlekotaRothFingerprintCount.xml',
 'KlekotaRothFingerprinter.xml',
 'MACCSFingerprinter.xml',
 'PubchemFingerprinter.xml',
 'SubstructureFingerprintCount.xml',
 'SubstructureFingerprinter.xml']

In [16]:
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [17]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [18]:
df = pd.read_csv('/content/SIRT1_05_bioactivity_data_2class_pIC50.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 729 entries, 0 to 728
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          729 non-null    int64
 1   molecule_chembl_id  729 non-null    object
 2   canonical_smiles    729 non-null    object
 3   class               729 non-null    object
 4   MW                  729 non-null    float64
 5   LogP                729 non-null    float64
 6   NumHDonors          729 non-null    float64
 7   NumHAcceptors       729 non-null    float64
 8   pIC50               729 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 51.4+ KB

In [19]:
df = pd.concat( [df['canonical_smiles'],df['molecule_chembl_id']], axis=1 )
df.to_csv('molecule.smi', sep='\t', index=False, header=False)
df

                                      canonical_smiles molecule_chembl_id
0                     NC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21       CHEMBL420311
1                      Cc1ccc2[nH]c3c(c2c1)CCCC3C(N)=O       CHEMBL115600
2                    NC(=O)C1CCCCc2c1[nH]c1ccc(Cl)cc21       CHEMBL446446
3                   CCOC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21       CHEMBL171137
4                     O=C(O)C1CCCc2c1[nH]c1ccc(Cl)cc21       CHEMBL171955
..                                                 ...                ...
724           O=C(NCCc1c[nH]c2ccccc12)c1n[nH]c2ccccc12      CHEMBL2093745
725    COc1ccc(N2CCN(c3nc(-c4ccccc4)nc4ccccc34)CC2)cc1      CHEMBL5405254
726  O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2Cl)ncc1C(=O)N...      CHEMBL5416344
727  O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2)nc(Nc2ccccc2...      CHEMBL5424599
728  COc1cc(Nc2nc(NCCCNC(=S)NCCC(=O)O)nc(Nc3ccccc3C...      CHEMBL5420622

[729 rows x 2 columns]

In [20]:
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [21]:
! pip install padelpy

Requirement already satisfied: padelpy in /usr/local/lib/python3.11/dist-packages (0.1.16)

In [22]:
from padelpy import padeldescriptor

fingerprint = 'SubstructureCount'

fingerprint_output_file = ''.join([fingerprint,'.csv']) #SubstructureCount.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='molecule.smi',
                d_file=fingerprint_output_file, #'SubstructureCount.csv'
                #descriptortypes='SubstructureCount.xml',
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

In [23]:
descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,SubFPC8,SubFPC9,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,CHEMBL420311,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,9.0,1.0,0.0,0.0,0.0,0.0,11.0
1,CHEMBL115600,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,10.0,10.0,1.0,0.0,0.0,0.0,0.0,11.0
2,CHEMBL446446,0.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,10.0,10.0,1.0,0.0,0.0,0.0,0.0,11.0
3,CHEMBL171137,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,10.0,10.0,3.0,0.0,0.0,0.0,0.0,11.0
4,CHEMBL171955,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,9.0,1.0,0.0,0.0,0.0,0.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,CHEMBL2093745,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,8.0,5.0,0.0,0.0,0.0,0.0,19.0
725,CHEMBL5405254,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,7.0,3.0,0.0,0.0,0.0,0.0,22.0
726,CHEMBL5416344,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,19.0,19.0,15.0,0.0,0.0,0.0,0.0,25.0
727,CHEMBL5424599,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,15.0,15.0,14.0,0.0,0.0,0.0,0.0,22.0
728,CHEMBL5420622,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,17.0,17.0,16.0,0.0,0.0,0.0,0.0,22.0